# Site settings
title: Babel
tagline: 用于编写下一代 JavaScript 的编译器
description: 用于编写下一代 JavaScript 的编译器
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://babeljs.cn/" # the base hostname & protocol for your site
twitter_username: babeljs
github_username: babel

deploy:
  type: git
  repository: git@github.com:docschina/babeljs.io.git
  branch: cn

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Makefile
  - Rakefile
  - package.json
  - js/repl/node_modules

include:
  - _redirects

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Blog Settings
permalink: /blog/:year/:month/:day/:title.html
paginate: 1
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

default_js:
  - "https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"
  - "https://cdn.bootcss.com/lodash.js/4.16.3/lodash.min.js"
  - "https://cdn.bootcss.com/bootstrap/3.3.1/js/bootstrap.min.js"
  - "https://cdn.bootcss.com/clipboard.js/1.5.13/clipboard.min.js"
  - "https://cdn.bootcss.com/docsearch.js/2.4.1/docsearch.min.js"
  - "/scripts/search.js"
  - "/scripts/clipboard.js"
  - "/scripts/open-in-repl.js"

# Compress HTML
compress_html:
  clippings: all
  comments: all
  # endings: all
  profile: false
  startings: [head, body]

# Get consistent pagination links with production
timezone: "-0500"
